export { Layout } from './layout/layout.component'
export { SnakeGame } from './game/game.component'
export { NavBar } from './layout/navbar/navbar.component'
export { ToggleButtons } from './toggle-buttons/toggle-buttons.component'
export { Instructions } from './instructions/instructions.component'
export { HighScore } from './high-score/high-score.component'